version: '2'
services:
  graphql_api:
    build: ./server
    volumes:
     - ./server/src:/src
    depends_on:
     - redis
  redis:
    extends:
      file: server/docker-compose.yml
      service: redis
  client:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - graphql_api
